"use client";
import { FormEvent, useEffect, useState } from "react";
import type { Recommendation } from "@perklah/rewards";

export default function Calculator(){
 const [signedIn,setSignedIn]=useState(false),[results,setResults]=useState<Recommendation[]>([]),[loading,setLoading]=useState(false),[owned,setOwned]=useState<string[]>([]),[message,setMessage]=useState("");
 useEffect(()=>{fetch("/api/session").then(r=>r.json()).then(x=>setSignedIn(x.signedIn));setOwned(JSON.parse(localStorage.getItem("perklah_owned_cards")||"[]"))},[]);
 function toggle(id:string){const next=owned.includes(id)?owned.filter(x=>x!==id):[...owned,id];setOwned(next);localStorage.setItem("perklah_owned_cards",JSON.stringify(next))}
 async function register(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const r=await fetch("/api/leads",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(Object.fromEntries(f))});const x=await r.json();if(!r.ok)return setMessage(x.error);setSignedIn(true);setMessage("")}
 async function calculate(e:FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);const f=new FormData(e.currentTarget);const body={amount:Number(f.get("amount")),merchant:String(f.get("merchant")),category:String(f.get("category")),channel:String(f.get("channel")),preference:String(f.get("preference")),currentMonthlySpend:Number(f.get("monthlySpend")||0)};const r=await fetch("/api/recommendations",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const x=await r.json();setResults(x.recommendations||[]);setLoading(false)}
 if(!signedIn)return <main className="wrap section"><div className="eyebrow">Free account required</div><h1>Unlock your card calculator.</h1><p className="muted">Create an account to save your wallet and see personalised card results.</p><form onSubmit={register} className="search" style={{gridTemplateColumns:"1fr 1fr"}}><input required name="name" placeholder="Full name"/><input required name="email" type="email" placeholder="Email address"/><input required name="phone" type="tel" placeholder="Singapore phone e.g. +65 8123 4567"/><input required name="password" type="password" minLength={8} placeholder="Create password (8+ characters)"/><label className="muted"><input name="marketingConsent" type="checkbox" value="true"/> Send me relevant card updates</label><button className="button green">Create account & continue</button>{message&&<p className="notice">{message}</p>}</form></main>;
 return <main className="wrap section"><div className="eyebrow">Decision calculator</div><h1>See every card. Know the threshold.</h1><form onSubmit={calculate} className="search" style={{gridTemplateColumns:"1fr 1fr"}}><input required name="amount" type="number" min="1" step="0.01" placeholder="Transaction amount (S$)"/><input required name="monthlySpend" type="number" min="0" step="0.01" placeholder="Your qualifying spend this month (S$)"/><input name="merchant" placeholder="Merchant (optional)"/><select name="category"><option>DINING</option><option>ONLINE</option><option>SHOPPING</option><option>GROCERIES</option><option>TRANSPORT</option></select><select name="channel"><option value="OFFLINE">In-store</option><option value="ONLINE">Online</option></select><select name="preference"><option value="BEST">Best overall</option><option value="CASHBACK">Cashback</option><option value="MILES">Miles</option><option value="POINTS">Points</option></select><button className="button green">{loading?"Checking…":"Calculate all cards"}</button></form><section className="section">{results.length===0?<p className="muted">Enter your transaction and monthly spend to compare every available card.</p>:results.map((r,i)=><article key={r.card.id} className="card result" style={{marginBottom:12,opacity:r.eligible?1:.7}}><div className="eyebrow">#{i+1} · {r.eligible?"Eligible now":"Not unlocked / not eligible"}</div><h3>{r.card.name} {owned.includes(r.card.id)&&<span className="tag">You have this card</span>}</h3><div className="stats"><span className="stat">{r.reward}</span><span className="stat">Value S${r.value.toFixed(2)}</span><span className="stat">Min monthly spend S${r.card.minimumSpend}</span>{r.card.monthlyCap&&<span className="stat">Cap S${r.card.monthlyCap}</span>}</div><label className="muted"><input checked={owned.includes(r.card.id)} onChange={()=>toggle(r.card.id)} type="checkbox"/> I have this card</label>{r.notes.map(n=><p className="muted" key={n}>{n}</p>)}</article>)}</section></main>
}
